development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

#development:
#  adapter: postgresql
#  encoding: unicode
#  database: f4_development
#  pool: 5
#  username: f4
#  password:

#test:
#  adapter: sqlite3
#  database: db/test.sqlite3
#  pool: 5
#  timeout: 500

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: 